#use_frameworks!

platform :ios, '8.0'

target 'FKCollectionView_Example' do
  pod 'FKCollectionView', :path => '../'
  pod 'SVProgressHUD'

  target 'FKCollectionView_Tests' do
    inherit! :search_paths

    
  end
end
